travis:
  secure:
    BINSTAR_TOKEN: J5XEwQLiA+qGy1RKq5462RrUh5XcJpDD66UTh34S/fsihfwTBzs91LPORN4kitF8Fkef12vAdvkBcEef2v+Or/saL0xAHAwHSG/FIhlVjOR9RYEjJiOsjJlYrbREMU/a7v9PNZY8hdbcbc6B1SVQWM7w4x1eprVE2MfmrqQOCrX+qmgnrbI8w/CJ7Y1nwB22rMvD2d7asYlx/nOViSBZ8kk+p0rjLd9oLv7fTX7IbobuxvUBRAkNnehkXWcbW7vy4/XLs1jIdg62iFqfBX+IpJf4QSeEq/CaQMyHjewphfKqfnzWI/yIBDGvbrm3P8wmiZ1BjRXd9HIKrFSPIqeaKFpYWqLvPaXumTcX2PQuMOcSit/x/b/oJ7NFaaTmiHeFRY5AAQw9ytR8cdqMgz9alH8oSOsX0Pfl/AZGBIxz7SGBqNp6xTK7CM6EuzpzKogbriJv6RipHs+Yor11OfjOJ0l5h6Dedq3xJ+NJ5zAuFesGuaSgU45okDNE/6u11lM+AeKyT20Xht6/VIuC+mFbGpRK0cjk+BCcbIJ0UOAJCYoZfV6WleioVp0LNdFZbflYGTv4Xv5rQ7bv2g5j3wtvYvYQOhrtgIAP3CnURDHbBQbmzIBc+JYXUoVUtYksLhEe0U234qLs6ZtNw61iOldxP+NdmPqMC/lMK9XIloe95dY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
